export const CURRENCIES: { [key: string]: { name: string; flag?: string } } = {
  usd: { name: 'US Dollar', flag: '🇺🇸' },
  eur: { name: 'Euro', flag: '🇪🇺' },
  gbp: { name: 'British Pound', flag: '🇬🇧' },
  chf: { name: 'Swiss Franc', flag: '🇨🇭' },
  cad: { name: 'Canadian Dollar', flag: '🇨🇦' },
  aud: { name: 'Australian Dollar', flag: '🇦🇺' },
  sek: { name: 'Swedish Krona', flag: '🇸🇪' },
  nok: { name: 'Norwegian Krone', flag: '🇳🇴' },
  rub: { name: 'Russian Ruble', flag: '🇷🇺' },
  thb: { name: 'Thai Baht', flag: '🇹🇭' },
  sgd: { name: 'Singapore Dollar', flag: '🇸🇬' },
  hkd: { name: 'Hong Kong Dollar', flag: '🇭🇰' },
  azn: { name: 'Azerbaijani Manat', flag: '🇦🇿' },
  amd: { name: '10 Armenian Dram', flag: '🇦🇲' },
  dkk: { name: 'Danish Krone', flag: '🇩🇰' },
  aed: { name: 'UAE Dirham', flag: '🇦🇪' },
  jpy: { name: '10 Japanese Yen', flag: '🇯🇵' },
  try: { name: 'Turkish Lira', flag: '🇹🇷' },
  cny: { name: 'Chinese Yuan', flag: '🇨🇳' },
  sar: { name: 'Saudi Riyal', flag: '🇸🇦' },
  inr: { name: 'Indian Rupee', flag: '🇮🇳' },
  myr: { name: 'Malaysian Ringgit', flag: '🇲🇾' },
  afn: { name: 'Afghan Afghani', flag: '🇦🇫' },
  kwd: { name: 'Kuwaiti Dinar', flag: '🇰🇼' },
  iqd: { name: '100 Iraqi Dinar', flag: '🇮🇶' },
  bhd: { name: 'Bahraini Dinar', flag: '🇧🇭' },
  omr: { name: 'Omani Rial', flag: '🇴🇲' },
  qar: { name: 'Qatari Rial', flag: '🇶🇦' },
  azadi1: { name: 'Azadi Coin' },
  emami1: { name: 'Emami Coin' },
  azadi1_2: { name: '½ Azadi Coin' },
  azadi1_4: { name: '¼ Azadi Coin' },
  azadi1g: { name: 'Gerami Coin' }
};